/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2023-07-16 18:39:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class registrationForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/nav.html", Long.valueOf(1689532793485L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light bg-dark text-white \">\r\n");
      out.write("<a class=\"navbar-brand text-white p-2 text-bold\">Online Job Portal</a>\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    \r\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0 nav-underline nav-fill\">\r\n");
      out.write("      	<li class=\"nav-item p-1\">\r\n");
      out.write("          <a class=\"nav-link active text-success \"  href=\"/JobApp/login.jsp\">Home</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item p-1\">\r\n");
      out.write("          <a class=\"nav-link active text-success\" aria-current=\"page\" href=\"/JobApp/joblisting.jsp\">Jobs</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item p-1\">\r\n");
      out.write("          <a class=\"nav-link active text-success\" aria-current=\"page\" href=\"/JobApp/profile.jsp\">Profile</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item p-1\">\r\n");
      out.write("          <a class=\"nav-link active text-success\" aria-current=\"page\" href=\"/JobApp/addVacancy.jsp\">+ Post Job</a>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      <form class=\"d-flex\">\r\n");
      out.write("        <input class=\"form-control me-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("        <button class=\"btn btn-outline-success\" type=\"submit\">Search</button>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"row p-5\">\r\n");
      out.write("      <div class=\"col-md-3\"></div>\r\n");
      out.write("      <div class=\"col-md-6\">\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h1 style=\"text-align: center\">Register New Account</h1>\r\n");
      out.write("            <br />\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("              <div class=\"col-md-4\"></div>\r\n");
      out.write("              <div class=\"col-md-4\">\r\n");
      out.write("                <img\r\n");
      out.write("                  style=\"width: 300px; height: 300px\"\r\n");
      out.write("                src=\"images/profilepic.png\"  alt=\"circle user avatar Icon 4035892\"\r\n");
      out.write("                  class=\"styles__Image-sc-2erpfv-1 eOQgUF\"\r\n");
      out.write("                />\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-4\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("                <br>\r\n");
      out.write("            <form method=\"post\" action=\"CreateUserServlet\" >\r\n");
      out.write("             <div class=\"row\">\r\n");
      out.write("              <div class=\"col-md-6 form-group\">\r\n");
      out.write("                <label>First Name</label\r\n");
      out.write("                ><input  name=\"fname\" class=\"form-control\" placeholder=\"First Name\" />\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-6\">\r\n");
      out.write("                <label>Last Name</label\r\n");
      out.write("                ><input  name=\"lname\" class=\"form-control\" placeholder=\"Last Name\" />\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-6\">\r\n");
      out.write("                <label>Address : </label\r\n");
      out.write("                ><input name=\"address\"  value=\"ln\" class=\"form-control\" placeholder=\"Address\" />\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-md-6 form-group\">\r\n");
      out.write("                <label>Telephone</label\r\n");
      out.write("                ><input  name=\"tp\"\r\n");
      out.write("                  class=\"form-control\"\r\n");
      out.write("                  type=\"number\"\r\n");
      out.write("                  placeholder=\"Telephone\"\r\n");
      out.write("                />\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-6\">\r\n");
      out.write("                <label>Email</label\r\n");
      out.write("                ><input  name=\"email\" class=\"form-control\" placeholder=\"Email\" />\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-md-6 form-group\">\r\n");
      out.write("                <label>NIC</label\r\n");
      out.write("                ><input  name=\"nic\"\r\n");
      out.write("                  class=\"form-control\"\r\n");
      out.write("                  placeholder=\"National Identity Card\"\r\n");
      out.write("                />\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-6\">\r\n");
      out.write("                <label>DOB</label\r\n");
      out.write("                ><input  name=\"dob\" class=\"form-control\" type=\"date\" placeholder=\"Date\" />\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-md-6 form-group\">\r\n");
      out.write("                <label>Password</label\r\n");
      out.write("                ><input  name=\"pass\"\r\n");
      out.write("                  class=\"form-control\"\r\n");
      out.write("                  placeholder=\"Password\"\r\n");
      out.write("                  type=\"password\"\r\n");
      out.write("                />\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-6\">\r\n");
      out.write("                <label>Confirm Password</label\r\n");
      out.write("                ><input  name=\"cpass\"\r\n");
      out.write("                  class=\"form-control\"\r\n");
      out.write("                  placeholder=\"Confirm Password\"\r\n");
      out.write("                  type=\"password\"\r\n");
      out.write("                />\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <br>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-4\"></div>\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("            <button class=\"btn btn-primary col-md-12\">Create Account</button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            </form>\r\n");
      out.write("             ");

				String message = (String) request.getAttribute("RegError");
				
      out.write("\r\n");
      out.write("				");

				if (message == null) {
				
      out.write("\r\n");
      out.write("				<div class=\"besideemailbox\" style=\"color: red\"></div>\r\n");
      out.write("				");

				} else if(message=="Successfully Saved Data !!")  {
				
      out.write("\r\n");
      out.write("				<div class=\"besideemailbox\" style=\"color: green\">");
      out.print(message );
      out.write("</div>\r\n");
      out.write("				");

				} else{ 
				
      out.write("\r\n");
      out.write("				<div class=\"besideemailbox\" style=\"color: red\">");
      out.print(message );
      out.write("</div>\r\n");
      out.write("				");
} 
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-md-3\"></div>\r\n");
      out.write("      <br><br>\r\n");
      out.write("    </div>\r\n");
      out.write("     <br><br>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
